fixed testCRPropa bug

diff --git a/.github/workflows/create_conda_package.yml b/.github/workflows/create_conda_package.yml
--- a/.github/workflows/create_conda_package.yml
+++ b/.github/workflows/create_conda_package.yml
@@ -7,40 +7,40 @@ on:
 
 
 jobs:
-  x64:
-    if: github.repository=='JanNiklasB/CRPropa3'
-    runs-on: ubuntu-22.04
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Preinstall
-        run: |
-          set -ex
-          ldd --version
-          conda init &> /dev/null
-          conda update -n base conda -y &> /dev/null
-          conda install conda-build anaconda-client -y &> /dev/null
-      - name: Build Conda Package
-        env:
-          accountName: ${{ secrets.ANACONDA_ACCOUNTNAME }}
-          token: ${{ secrets.ANACONDA_TOKEN }}
-        run: |
-          set -ex
-          conda init &> /dev/null
-          cd conda-bld
-          conda config --set anaconda_upload yes 
-          conda build -m conda_build_config.yaml -c conda-forge . \
-            --user $accountName \
-            --token $token \
-            | tee build.log
-      - name: Archive Build Logs
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: "Anaconda_Build_Log"
-          path: conda-bld/build.log
+  # x64:
+  #   if: github.repository=='JanNiklasB/CRPropa3'
+  #   runs-on: ubuntu-22.04
+  #   strategy:
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #     - name: Preinstall
+  #       run: |
+  #         set -ex
+  #         ldd --version
+  #         conda init &> /dev/null
+  #         conda update -n base conda -y &> /dev/null
+  #         conda install conda-build anaconda-client -y &> /dev/null
+  #     - name: Build Conda Package
+  #       env:
+  #         accountName: ${{ secrets.ANACONDA_ACCOUNTNAME }}
+  #         token: ${{ secrets.ANACONDA_TOKEN }}
+  #       run: |
+  #         set -ex
+  #         conda init &> /dev/null
+  #         cd conda-bld
+  #         conda config --set anaconda_upload yes 
+  #         conda build -m conda_build_config.yaml -c conda-forge . \
+  #           --user $accountName \
+  #           --token $token \
+  #           | tee build.log
+  #     - name: Archive Build Logs
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: "Anaconda_Build_Log"
+  #         path: conda-bld/build.log
 
   arm:
     if: github.repository=='JanNiklasB/CRPropa3'
@@ -54,7 +54,7 @@ jobs:
         run: |
           set -ex
           ldd --version
-          conda init &> /dev/null
+          conda init
           conda update -n base conda -y &> /dev/null
           conda install conda-build anaconda-client -y &> /dev/null
       - name: Build Conda Package
